/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_uka_ilkd_key_dl_arithmetics_impl_csdp_CSDP */

#ifndef _Included_de_uka_ilkd_key_dl_arithmetics_impl_csdp_CSDP
#define _Included_de_uka_ilkd_key_dl_arithmetics_impl_csdp_CSDP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_uka_ilkd_key_dl_arithmetics_impl_csdp_CSDP
 * Method:    easySDP
 * Signature: ([II[D[D[DD[D[D[D[D[D)I
 */
JNIEXPORT jint JNICALL Java_de_uka_ilkd_key_dl_arithmetics_impl_csdp_CSDP_easySDP
  (JNIEnv *, jclass, jintArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdouble, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     de_uka_ilkd_key_dl_arithmetics_impl_csdp_CSDP
 * Method:    test2
 * Signature: (II[D[D[DD[D[D[D[D[D)I
 */
JNIEXPORT jint JNICALL Java_de_uka_ilkd_key_dl_arithmetics_impl_csdp_CSDP_test2
  (JNIEnv *, jclass, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdouble, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     de_uka_ilkd_key_dl_arithmetics_impl_csdp_CSDP
 * Method:    test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_uka_ilkd_key_dl_arithmetics_impl_csdp_CSDP_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
