// This file is part of KeY - Integrated Deductive Software Design
// Copyright (C) 2001-2005 Universitaet Karlsruhe, Germany
//                         Universitaet Koblenz-Landau, Germany
//                         Chalmers University of Technology, Sweden
//
// The KeY system is protected by the GNU General Public License. 
// See LICENSE.TXT for details.
//
//

/* Generated by Together */

package de.uka.ilkd.key.logic.op;

import de.uka.ilkd.key.logic.DLWaryClashFreeSubst;
import de.uka.ilkd.key.logic.Name;
import de.uka.ilkd.key.logic.Term;

public class DLWarySubstOp extends SubstOp {

    public DLWarySubstOp(Name name) {
	super(name);
    }

    /**
     * Apply this substitution operator to <code>term</code>, which
     * has this operator as top-level operator
     */
    public Term apply ( Term term ) {
	QuantifiableVariable v=term.varsBoundHere(1).get(0);
	DLWaryClashFreeSubst cfSubst = new DLWaryClashFreeSubst(v, term.sub(0));
	Term res = cfSubst.apply(term.sub(1));
	return res;	
    }    
}
