classes: rational.scala parse.scala arithmetic.scala parallel.scala
	fsc -optimise rational.scala parse.scala arithmetic.scala parallel.scala

jar:
	jar cmf manifest Cohenhormander.jar cohenhormander

all: classes jar