#!/bin/sh
# standard lib location
if [ -z "$KEY_LIB" ] ; then
   KEY_LIB="../key-ext-jars"
fi

key_ext_jars="antlr.jar log4j.jar JLink/JLink.jar orbital-core.jar orbital-ext.jar scala-library.jar recoderKey.jar commons-compress-1.4.jar"

key_dev_jars="javacc.jar junit.jar junit-4.4.jar"


CLASSPATH=./binary/

if [ ! -f "$KEY_LIB/antlr-2.7.2.jar" ]
then
   echo "Cannot find $KEY_LIB/antlr-2.7.2.jar"
   echo Copy or link the file into the
   echo "$KEY_LIB/ directory."
   exit 1
else
   ANTLR_2_7_2="$KEY_LIB/antlr-2.7.2.jar"
fi

for i in $key_ext_jars $key_dev_jars; do
    current_jar="$KEY_LIB/$i"
    if [ ! -f $current_jar ]
    then
       echo "Cannot find $current_jar."
       echo Copy or link the file into the
       echo "$KEY_LIB/ directory."
       exit 1
    else
       CLASSPATH=$CLASSPATH:$current_jar
    fi
done

export CLASSPATH
echo "CLASSPATH=$CLASSPATH" > Makefile.mk
export ANTLR_2_7_2
echo "ANTLR_2_7_2=$ANTLR_2_7_2" >> Makefile.mk
