/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * Assign is used to represent an assignment.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface Assign extends ElementaryDLProgram {
    /** @link aggregation */

    /* # Expression lnkExpression; */

    /** @link aggregation */

    /* # ProgramVariable lnkVariable; */
}
