/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * Tagging interface for atomic terms.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface AtomicTerm extends Expression {
}
