/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * Biimplies represents a logical equivalance
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface Biimplies extends CompoundFormula {
}
