/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * Choice is the non-deterministic choice between two DLPrograms.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface Choice extends CompoundDLProgram {
}
