/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * Chop represents the sequential composition of DLPrograms.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface Chop extends CompoundDLProgram {
}
