/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * CompoundDLProgram is the superinterface of all non-elementary DLPrograms.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface CompoundDLProgram extends DLProgram,
        DLNonTerminalProgramElement {
    /** @link aggregation */

    /* # DLProgram lnkFormulaElement; */
}
