/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * CompoundFormula is the super interface of all non-elementary formulas
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface CompoundFormula extends Formula, DLNonTerminalProgramElement {
    /** @link aggregation */

    /* # Formula lnkFormula; */
}
