/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * Comparsion is the super interface of all comparsion operations (<, <=, =,
 * >=, >).
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface Comparsion extends Predicate, SymbolizedElement {
}
