/* Generated by Together */

package de.uka.ilkd.key.dl.model;

import java.math.BigDecimal;

/**
 * A constant represents a constant number. In context of dL this is real valued
 * constant.
 * 
 * @author jdq
 * @since Tue Jan 16 16:11:53 CET 2007
 */
public interface Constant extends DLTerminalProgramElement,
        ElementaryExpression, AtomicTerm {
    /**
     * Get the value of the constant
     * 
     * @return the value of the constant
     */
    BigDecimal getValue();
}
