/* Generated by Together */

package de.uka.ilkd.key.dl.model;

import java.util.ArrayList;

import de.uka.ilkd.key.dl.formulatools.Prog2LogicConverter;
import de.uka.ilkd.key.gui.Main;
import de.uka.ilkd.key.logic.TermBuilder;

/**
 * The DiffSystem is used to represent the elementary DLProgram of a system of
 * differential equations and invariants.
 * 
 * @author jdq
 * @since 13.02.2007
 */
public interface DiffSystem extends ElementaryDLProgram {
    /**
     * @link aggregation
     */
    /* # Formula lnkFormula; */
    
}
