/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * Div represents the arthmetic division.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface Div extends Function {
}
