/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * DLBottom is the interface implementing *ALL* interfaces used in the context
 * of DL. It is used to give the ProgramSV the possible to stand for every
 * single object.
 * 
 * @author jdq
 * @since 13.02.2007
 * @see de.uka.ilkd.key.logic.op.ProgramSV
 */
public interface DLBottom extends DLProgram, Formula, Comparsion, Expression,
        ProgramVariable, Function, DiffSystem, RandomAssign {
}
