/* Generated by Together */

package de.uka.ilkd.key.dl.model;

import de.uka.ilkd.key.java.NonTerminalProgramElement;
import de.uka.ilkd.key.java.ProgramElement;

/**
 * The DLNonTerminalProgramElement is the super interface of compound
 * {@link DLProgramElement}s. The children can be accesed using the methods of
 * {@link NonTerminalProgramElement}.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface DLNonTerminalProgramElement extends NonTerminalProgramElement,
        DLProgramElement, SymbolizedElement, Iterable<ProgramElement> {
    /**
     * @return true if the element should be printed in infix notation or
     *         prefixed.
     */
    boolean printInfix();
}
