/* Generated by Together */

package de.uka.ilkd.key.dl.model;

import de.uka.ilkd.key.java.Statement;

/**
 * A DLProgram is a top level program.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface DLProgram extends DLProgramElement, Statement {
}
