/* Generated by Together */

package de.uka.ilkd.key.dl.model;

import java.io.Serializable;

import de.uka.ilkd.key.java.ProgramElement;
import de.uka.ilkd.key.java.ReuseableProgramElement;

/**
 * Every element that can occur in a hybrid program implements this interface.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface DLProgramElement extends ProgramElement, Serializable, ReuseableProgramElement {

}