/* Generated by Together */

package de.uka.ilkd.key.dl.model;

import de.uka.ilkd.key.java.TerminalProgramElement;

/**
 * {@link DLTerminalProgramElement} represents elementary
 * {@link DLProgramElement}s.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface DLTerminalProgramElement extends TerminalProgramElement,
        DLProgramElement {
}
