/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * Dot represents a diveration (e.g. x'). It stores the order to represent
 * higher dirivations (e.g. x''). We assume that dirivations are always of the
 * form d/dt, so we dont need to store the dimension of the diveration.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface Dot extends ElementaryExpression, DLNonTerminalProgramElement {
    /**
     * Get the order of the diveration
     * 
     * @return the order of the diveration
     */
    int getOrder();

    /** @link aggregation */

    /* # ProgramVariable lnkVariable; */
}
