/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * ElementaryExpression represents an elementary expression, e.g. a
 * {@link Constant} or {@link Variable}.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface ElementaryExpression extends Expression {
}
