/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * Represents an elementary, thus not compound
 * {@link CompoundDLProgram), DLProgram.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface ElementaryDLProgram extends DLProgram,
        DLNonTerminalProgramElement {
}
