/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * Interface representing the equals (=) predicate.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface Equals extends Comparsion {
}
