/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * Interface representing the exponential function (exp, ^).
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface Exp extends Function {
}
