/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * Super interface of all expressions.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface Expression extends DLProgramElement {
}
