/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * Super interface of all formulas
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface Formula extends DLProgramElement {
}
