/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * An predicate that is not specially interpreted by KeY.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface FreePredicate extends Predicate {
}
