/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * Interface representing a free function. Free does only mean that KeY does not
 * know the meaning of this function, it can be something like the sinus or
 * cosinus or somthing.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface FreeFunction extends Function {
}
