/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * A FunctionTerm is the concartination operator used to make it possible to
 * have singleton functions.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface FunctionTerm extends DLNonTerminalProgramElement, Expression,
        AtomicTerm {
    /** @link aggregation */
    /* # Expression lnkExpression; */

    /* # Function lnkFunction; */
    /* # Function lnkFunction; */

    /**
     * @link aggregation
     */
    /* # Expression lnkExpression; */
}
