/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * GreaterEquals represents the common greater equals predicate (>=).
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface GreaterEquals extends Comparsion {
}
