/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * Greater represents the common greater predicate (>).
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface Greater extends Comparsion {
}
