/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * Implies represents the implication (->).
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface Implies extends CompoundFormula {
}
