/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * Less represents the common Less predicate (<).
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface Less extends Comparsion {
}
