/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * LessEquals represents the common less equals predicate (<=).
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface LessEquals extends Comparsion {
}
