/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * LogicalVariable is used to represent logical variables, meaning variables
 * whose value cannot be changed by the program.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface LogicalVariable extends Variable {
}
