/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * MinusSign represents the unary minus.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface MinusSign extends Function {
}
