/* Generated by Together */

package de.uka.ilkd.key.dl.model;

import de.uka.ilkd.key.logic.Name;

/**
 * This interface is implemented by every object that is explictly named.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface NamedElement {
    Name getElementName();
}
