/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * Not represents the logical negation.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface Not extends CompoundFormula {
}
