/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * Or represents the disjunction operator.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface Or extends CompoundFormula {
}
