/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * Predicate is the super interface of all predicates ({@link FreePredicate},
 * {@link Comparsion},...).
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface Predicate extends DLTerminalProgramElement, NamedElement {
}
