/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * The PredicateTerm represents the concartenation operation on predicates and
 * its parameters. It is used to make singleton predicates possible.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface PredicateTerm extends Formula, DLNonTerminalProgramElement {
    /** @link aggregation */
    /* # Expression lnkInterface1; */

    /**
     * @link aggregation
     */
    /* # Predicate lnkPredicate; */
}
