/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * ProgramVariable is the representation of non-rigid functions without
 * parameters in DLPrograms.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface ProgramVariable extends Variable {
}
