/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * Quest is the elementary program representing a formula. The semantics is that
 * it acts as a NOOP if the formula is true and as stop otherwise.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface Quest extends ElementaryDLProgram {
    /** @link aggregation */

    /* # Formula lnkFormula; */
}
