/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * Star represents the non-deterministic repetition of a program.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface Star extends CompoundDLProgram {
    public Formula getInvariant();
}
