/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * This interface is implemented by all elements that are represented by a
 * special symbol such as '+' or '-'.
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface SymbolizedElement {
    /**
     * Returns the symbol representing this element.
     * 
     * @return the symbol representing this element.
     */
    String getSymbol();
}
