/* Generated by Together */

package de.uka.ilkd.key.dl.model;

/**
 * The super interface of all variables ({@link ProgramVariable},
 * {@link LogicalVariable})
 * 
 * @author jdq
 * @since 13.02.2007
 * 
 */
public interface Variable extends ElementaryExpression,
        DLTerminalProgramElement, AtomicTerm, NamedElement {
}
